apiVersion: kustomize.config.k8s.io/v1beta1
kind: Kustomization
resources:
  - namespace.yaml
  - operatorgroup.yaml
  - subscription.yaml
  - orchestrator.yaml
  - storageclass.yaml
  - volumesnapshotclass.yaml
  - from-metadata-rbac.yaml
  - from-metadata-job.yaml
