apiVersion: kustomize.config.k8s.io/v1beta1
kind: Kustomization
resources:
  - gitops-controller-rbac.yaml
  - ../operators/trident
  - ../operators/cnv
  - ../operators/bgp-cloud-connector
  - ../samples/cudn
