apiVersion: shipwright.io/v1beta1
kind: BuildRun
metadata:
  name: operator-2b6ad939
  namespace: openshift-bgp-cloud-connector
  annotations:
    argocd.argoproj.io/sync-wave: "-1"
    argocd.argoproj.io/sync-options: SkipDryRunOnMissingResource=true
spec:
  build:
    name: operator
  serviceAccount: shipwright-build
  timeout: 60m
  stepResources:
    - name: build-and-push
      resources:
        requests:
          cpu: "2"
          memory: 4Gi
        limits:
          cpu: "4"
          memory: 8Gi
