apiVersion: build.openshift.io/v1
kind: BuildConfig
metadata:
  name: operator
  namespace: openshift-bgp-cloud-connector
  annotations:
    argocd.argoproj.io/sync-wave: "-1"
    argocd.argoproj.io/sync-options: SkipDryRunOnMissingResource=true
spec:
  runPolicy: Serial
  source:
    type: Git
    git:
      uri: https://github.com/openshift/bgp-cloud-connector.git
      ref: main
  strategy:
    type: Docker
    dockerStrategy:
      dockerfilePath: Dockerfile
  output:
    to:
      kind: ImageStreamTag
      name: operator:dev
  resources:
    requests:
      cpu: "2"
      memory: 4Gi
    limits:
      cpu: "4"
      memory: 8Gi
  successfulBuildsHistoryLimit: 3
  failedBuildsHistoryLimit: 3
  triggers:
    - type: ConfigChange
    - type: ImageChange
      imageChange: {}
